# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='anio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.Anio'),
        ),
        migrations.AddField(
            model_name='plan',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.Carrera'),
        ),
    ]
