# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identificador', models.CharField(default='', help_text='<sup>Escriba una letra para identifique la actividad</sup>', max_length=1, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='anio',
            options={'ordering': ['-nombre']},
        ),
        migrations.AlterModelOptions(
            name='bloque',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-nombre']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bloque',
            name='hora_inicio',
            field=models.TimeField(default='00:00', verbose_name='Hora Inicio'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='hora_termino',
            field=models.TimeField(default='00:00', verbose_name='Hora de Termino'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Carrera'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='horas_ayudantia',
            field=models.IntegerField(default=0, verbose_name='Horas de Ayudantía'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='nombre',
            field=models.IntegerField(default=0, help_text='<sup>Indique un número entre 1 y 15\n                                        para identificar el bloque</sup>', validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Semestre'),
        ),
    ]
