# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_auto_20161107_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
    ]
