# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0003_auto_20161109_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
