# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0004_auto_20161109_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='credito',
        ),
        migrations.AddField(
            model_name='modulo',
            name='creditos',
            field=models.IntegerField(default=0, verbose_name='Créditos'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='horas_clase',
            field=models.IntegerField(default=0, verbose_name='Horas de clase'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='horas_laboratorio',
            field=models.IntegerField(default=0, verbose_name='horas de laboratorio'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='horas_seminario',
            field=models.IntegerField(default=0, verbose_name='Horas de seminario'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='horas_taller',
            field=models.IntegerField(default=0, verbose_name='Horas de Taller'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Modulo'),
        ),
    ]
