# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0005_auto_20161110_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='correo',
            field=models.EmailField(default='', max_length=100, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='rut',
            field=models.CharField(default='', max_length=12, verbose_name='RUT'),
        ),
    ]
