# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque1', models.CharField(max_length=1)),
                ('bloque2', models.CharField(max_length=1)),
                ('bloque3', models.CharField(max_length=1)),
                ('bloque4', models.CharField(max_length=1)),
                ('bloque5', models.CharField(max_length=1)),
                ('bloque6', models.CharField(max_length=1)),
                ('bloque7', models.CharField(max_length=1)),
                ('bloque8', models.CharField(max_length=1)),
                ('bloque9', models.CharField(max_length=1)),
                ('bloque10', models.CharField(max_length=1)),
                ('dia_semana', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoProfesorModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Modulo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Profesor')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='periodoprofesormodulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.PeriodoProfesorModulo'),
        ),
    ]
