# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoProfesorModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Modulo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Profesor')),
            ],
        ),
    ]
