# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeriodoProfesorModelo',
            new_name='PeriodoProfesorModulo',
        ),
    ]
