# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_auto_20170704_1335'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaBloqueProtegido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservado', models.BooleanField(default=False)),
                ('bloque', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Bloque')),
            ],
            options={
                'ordering': ['bloque'],
            },
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque1',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque10',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque2',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque3',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque4',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque5',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque6',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque7',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque8',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='bloque9',
        ),
        migrations.AddField(
            model_name='horario',
            name='bloque',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Bloque'),
        ),
        migrations.AddField(
            model_name='horario',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodoprofesormodulo',
            name='carrera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Carrera'),
        ),
        migrations.AddField(
            model_name='periodoprofesormodulo',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Plan'),
        ),
        migrations.AlterField(
            model_name='periodoprofesormodulo',
            name='modulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Modulo'),
        ),
        migrations.AlterField(
            model_name='periodoprofesormodulo',
            name='periodo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Periodo'),
        ),
        migrations.AlterField(
            model_name='periodoprofesormodulo',
            name='profesor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parametros.Profesor'),
        ),
    ]
